# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\"\n\x0c\x43heckRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"E\n\rCheckResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\x11\n\tavailable\x18\x03 \x01(\x08\"N\n\x0eReserveRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x16\n\x0ereservation_id\x18\x03 \x01(\t\"L\n\x0fReserveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0fremaining_stock\x18\x03 \x01(\x05\"\r\n\x0bListRequest\":\n\x07Product\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05stock\x18\x03 \x01(\x05\"4\n\x0cListResponse\x12$\n\x08products\x18\x01 \x03(\x0b\x32\x12.inventory.Product2\xe3\x01\n\x10InventoryService\x12\x43\n\x0e\x43heckInventory\x12\x17.inventory.CheckRequest\x1a\x18.inventory.CheckResponse\x12I\n\x10ReserveInventory\x12\x19.inventory.ReserveRequest\x1a\x1a.inventory.ReserveResponse\x12?\n\x0cListProducts\x12\x16.inventory.ListRequest\x1a\x17.inventory.ListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKREQUEST']._serialized_start=30
  _globals['_CHECKREQUEST']._serialized_end=64
  _globals['_CHECKRESPONSE']._serialized_start=66
  _globals['_CHECKRESPONSE']._serialized_end=135
  _globals['_RESERVEREQUEST']._serialized_start=137
  _globals['_RESERVEREQUEST']._serialized_end=215
  _globals['_RESERVERESPONSE']._serialized_start=217
  _globals['_RESERVERESPONSE']._serialized_end=293
  _globals['_LISTREQUEST']._serialized_start=295
  _globals['_LISTREQUEST']._serialized_end=308
  _globals['_PRODUCT']._serialized_start=310
  _globals['_PRODUCT']._serialized_end=368
  _globals['_LISTRESPONSE']._serialized_start=370
  _globals['_LISTRESPONSE']._serialized_end=422
  _globals['_INVENTORYSERVICE']._serialized_start=425
  _globals['_INVENTORYSERVICE']._serialized_end=652
# @@protoc_insertion_point(module_scope)
